server:
  port: 8080
  servlet:
    context-path: /

spring:
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  type-aliases-package: cn.pridezh.**.domain.po
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

app:
  repository: D://repository/
  database: data.db
  auth:
    password: